name: Generate Snake Animation

on:
  schedule: # Executa a cada 12 horas
    - cron: "0 */12 * * *"

  workflow_dispatch: # Permite executar manualmente

  push:
    branches:
    - main

jobs:
  generate:
    permissions:
      contents: write # Permissões para escrever o conteúdo gerado
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark # Define a paleta de cores

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
